### ISSUE TITLE
Workday changed

### ISSUE THREAD

**Issue by kush5683** [GregoryConrad/WorkdayScheduleExporter#9]
Hey Workday changed the layout of the view my course page so the extension is broken. Not sure if you're interested in maintaining this project while you're still a student or not but I thought I'd let you know regardless.

**Comment by GregoryConrad** [comment]
@kush5683 Thanks for letting me know; I'll take a look

**Comment by GregoryConrad** [comment]
@kush5683 I can't replicate the issue; could you please send me a screenshot/video demonstrating the issue?

**Comment by kush5683** [comment]
Huh, weird. I can't get the same behavior as yesterday. Worked fine for me today lol.
